# Generated by Django 4.2.3 on 2023-07-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس ای پی')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='private',
            field=models.BooleanField(default=False, verbose_name='...خصوصی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='video_not_music',
            field=models.FileField(blank=True, null=True, upload_to='video/', verbose_name='استیکر'),
        ),
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='pages.ipaddress', verbose_name='بازدید ها'),
        ),
    ]
