# Generated by Django 4.2.3 on 2023-07-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_ipaddress_alter_article_private_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='pages.category', verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس برای توییت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='post',
            field=models.TextField(max_length=1000, verbose_name='توییت'),
        ),
    ]
